config/routes.rb
Saai2::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :lists do
    resources :filas
  end

  get 'hangman', to: 'hangman#index', as: 'hangman'
  get 'hangman/game', to: 'hangman#game', as: 'hangman_game'
  post 'hangman/game', to: 'hangman#game', as: 'hangman_save'
  get 'users/menu', to: 'users#menu'
  get 'ranking', to: 'users#ranking'
  get "actividades/", to: 'actividades#index'
  post "actividades/video", to: 'actividades#video'
  get "actividades/videolist", to: 'actividades#videolist'
  post "actividades/videolist", to: 'actividades#videolist'
  get "tuttifrutti", to: 'tuttifrutti#index'
  post "tuttifrutti/agregarPuntos", to: 'tuttifrutti#agregarPuntos'
  get "seleccion", to: 'actividades#seleccion'
  root :to => "users#menu"
  

end

app/models/fila.rb
class Fila < ActiveRecord::Base
  belongs_to :list
  def self.random_word
	Fila.offset(rand(Fila.count)).first.palabra.upcase
  end	

  #palabra
  validates :palabra, presence: true
  #significado
  validates :significado, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :filas
  belongs_to :user

  #nombre
  validates :nombre, presence: true
  #idiomaNativo
  validates :idiomaNativo, presence: true
  #idiomaForaneo
  validates :idiomaForaneo, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists

  #nombre
  validates :nombre, presence: true
  #apellido
  validates :apellido, presence: true
  #email
  validates :email, presence: true
  validates :email, uniqueness: true
  #foto
  validates :foto, :format => URI::regexp(%w(http https)), :allow_blank => true
  #idiomasNativos
  validates :idiomasNativos, presence: true
  #idiomasAAprender
  validates :idiomasAAprender, presence: true
end

app/controllers/actividades_controller.rb
class ActividadesController < ApplicationController
  require 'youtube_it'

  def index
  end

  def video
  	@videoid = params[:videoid]
  end

  def seleccion
  end

  def videolist
  	client = YouTubeIt::Client.new
  	if !(params[:cantidad])
  		@maxresults = 3
  	else
  	    @maxresults = params[:cantidad]
  	end
  	reply = client.videos_by(:query => "aprender ingles en español", :max_results => @maxresults, :restriction => 'ES', :fields => {:view_count => "5000"} )
  	@videos = reply.videos
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/filas_controller.rb
class FilasController < ApplicationController

def create
    @list = List.find(params[:list_id])
    @fila = @list.filas.create(params[:fila].permit(:palabra, :significado, :idiomaNativo, :idiomaForaneo, :imagen, :audio, :sinonimos, :antonimos))
    redirect_to list_path(@list)
end

def update
	@fila = Fila.find(params[:id])

  p = { params[:name] => params[:value] }

	respond_to do |format|
		if @fila.update_attributes(p)
			format.html { redirect_to @fila, notice: 'Fila was successfully updated.'}
			format.json { render json: @fila }
		else
			format.html { render action: "edit"}
			format.json { render json: @fila.errors, status: :unproccessable_entity }
		end
	end
end

end

app/controllers/hangman_controller.rb
# encoding: utf-8

class HangmanController < ApplicationController

  def index
    resetGame()
    redirect_to hangman_game_path
  end

  def game

    if !session[:current_word]
      resetGame()
    end

    if session[:turns_left] > 0 && params[:letter] && params[:letter].length > 0

      session[:turns_left] -= 1

      if !UnicodeUtils.upcase(session[:used_letters]).include?(UnicodeUtils.upcase(params[:letter].chars.first))
        session[:used_letters] += UnicodeUtils.upcase(params[:letter].chars.first)
      end

    end

    if session[:turns_left] > 0 && params[:palabra] && params[:palabra].length > 0
      if UnicodeUtils.upcase(params[:palabra]) == UnicodeUtils.upcase(session[:current_word_sinsplit])
        session[:palabra_adivinada] = true
        @palabra = params[:palabra].titleize
        current_user.puntosPrivados = current_user.puntosPrivados + 25
        current_user.save
      else
        session[:turns_left] -= session[:turns_left]
        @palabra = params[:palabra].titleize
      end
    end

    

    @turns_left = session[:turns_left]
    @used_letters = session[:used_letters]
    @word = []
    @correct_letters = 0
    @palabra_adivinada = session[:palabra_adivinada]

    session[:current_word].each do |letter|
      if UnicodeUtils.upcase(@used_letters).include?(UnicodeUtils.upcase(letter))
        @word.push(UnicodeUtils.upcase(letter))
        @correct_letters += 1
        if @correct_letters == session[:current_word].length
          current_user.puntosPrivados = current_user.puntosPrivados + 10
          current_user.save
        end
      else
        @word.push("_")
      end
    end

  end

  private
    def resetGame
      #dictionary = [ "hier", "kommt", "sonne", "welt", "zählt", "laut", "zehn" ]
      #session[:current_word] = dictionary.sample.split("")
      session[:current_word_sinsplit] = Fila.random_word
	    session[:current_word] = session[:current_word_sinsplit].split("")
      session[:used_letters] = ""
      session[:turns_left] = 10
      session[:palabra_adivinada] = false
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :authenticate_user!

  def new
    @list = current_user.lists.build
  end
  
  def index
  @lists = current_user.lists
  end
  
  def create
  @list = List.new(list_params)
  @list.user_id = current_user.id
  @list.save
  
  redirect_to @list
  end
  
  def show
  @list = List.find(params[:id])
  end
  
  def edit
  @list = List.find(params[:id])
  end
  
  def update
  @list = List.find(params[:id])  
 
  if @list.update(params[:list].permit(:nombre, :idiomaNativo, :idiomaForaneo))
    redirect_to @list
  else
    render 'edit'
  end
  end

  def destroy
  @list = List.find(params[:id])
  @list.destroy
 
  redirect_to lists_path
  end
  
  private
  def list_params
    params.require(:list).permit(:nombre, :idiomaNativo, :idiomaForaneo)
  end

  def set_list
    @list = current_user.lists.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  before_filter :configure_permitted_parameters

protected
# my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :nombre, :apellido, :idiomasNativos, :idiomasAAprender, :password, :password_confirmation)
    end
   devise_parameter_sanitizer.for(:account_update) do |u|
     u.permit(:email, :idiomasNativos, :idiomasAAprender, :foto, :password, :password_confirmation, :current_password)
     end
  end
end

app/controllers/tuttifrutti_controller.rb
class TuttifruttiController < ApplicationController
  def index
  end

  def agregarPuntos
  	current_user.update_attributes(puntosPrivados: current_user.puntosPrivados + params[:puntos_hidden].to_i)
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @count = List.where(user_id: 1).count
  end

  def menu
  end

  def ranking
  	@usersPuntosPublicos = User.order("puntosPublicos desc").limit(3)
  	@usersPuntosPrivados = User.order("puntosPrivados desc").limit(3)
  	#@usersLists = User.find_by_sql("SELECT users.nombre, count(lists.user_id) AS cantidad 
  	#	FROM users INNER JOIN lists ON users.id = lists.user_id 
  	#	GROUP BY users.nombre 
  	#	ORDER BY cantidad Desc;")
    @usersLists = User.select("users.*, COUNT(lists.id) AS count_lists")
    .joins("LEFT OUTER JOIN lists ON users.id = lists.user_id")
    .group("users.id")
    .order("count_lists DESC")

  end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filas_helper.rb
module FilasHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tuttifrutti_helper.rb
module TuttifruttiHelper
end

app/views/actividades/_prodem.html.erb
<div id="prodem">
	<h3>Pronombres demostrativos</h3>
	<p>Es importante comenzar señalando que los pronombres pueden estar en singular o plural y que pueden hacer referencia a la distancia.</p>
	<div><span>this</span><strong>This</strong> <span>(Este/a/o)</span>,<span>That</span><strong>that</strong> <span>(Ese/a/o, aquél, aquello/a)</span>, <span>These</span><strong>these</strong> <span>(Estos/as)</span>, <span>Those</span><strong>those</strong> <span>(Esos/as, aquellos/as)</span></div>
	<ul class="tablasaprender">
		<li>Ejemplos:</li>
		<li>Singular and here (singular y aquí):</li>
		<li><span>I like this car.</span>I like <span>this</span> car. <span>(Me gusta este coche.)</span></li>
		<li >Singular and there (singular y allí):</li>
		<li><span>I like that car.</span>I like <span>that</span> car. <span>(Me gusta ese coche.)</span></li>
		<li>Plural and here (plural y aquí):</li>
		<li><span>I like these cars.</span>I like <span>these</span> cars. <span>(Me gustan estos coches.)</span></li>
		<li>Plural and there (plural y allí):</li>
		<li><span>I like those cars.</span>I like<span> those</span> cars.<span> (Me gustan aquellos coches.) </span></li>
	</ul>
	<h3>Other Uses of Demonstrative Pronouns (Otros usos de los demostrativos)</h3>
	<ol class="tablasaprender">
		<ol>
			<li>Podemos utilizarlos cuando nos presentamos a otra persona al otro lado de la línea telefónica:
				<ul>
					<li><span>Hello. This is Alicia.</span>Hello. <span>This</span> is Alicia.<span> (Hola. Soy Alicia.) </span></li>
				</ul>
			</li>
			<li>O cuando no estamos seguros de con quién estamos hablando al otro lado de la línea o a alguien que no vemos porque estamos en un sitio oscuro o en otra habitación:
				<ul>
					<li><span>Peter, is that you?</span>Peter, is <span>that</span> you? <span>(¿Eres tú, Peter?) </span></li>
				</ul>
			</li>
			<li>"<strong>This</strong>", también lo podemos utilizar cuando presentamos a personas:
				<ul>
					<li><span>Lucy, this is my friend Jill.</span>Lucy, <span>this</span> is my friend Jill. <span>(Lucy, ésta es mi amiga Jill.) </span></li>
				</ul>
			</li>
			<li>"<strong>That</strong>", también lo podemos utilizar para referirnos a algo del pasado:
				<ul>
					<li><span>That pizza was delicious.</span><span>That</span> pizza was delicious. <span>(Aquella pizza estaba riquísima.) </span></li>
				</ul>
			</li>
		</ol>
	</ol>
</div>

app/views/actividades/_proper.html.erb
<div id="proper">
	<h3>Pronombres Personales</h3>
	<table class="tablasaprender table table-striped table-condensed table-hover">
		<tbody>
			<tr class="principal">
				<td colspan="2">Pronombres personales <br>(función de sujeto)</td>
				<td>Ejemplo</td>
				<td>Traducción ejemplo</td>
			</tr>
			<tr>
				<td><strong>I</strong></td>
				<td>yo</td>
				<td><strong>I</strong> am ill.</td>
				<td>Yo estoy enfermo.</td>
			</tr>
			<tr>
				<td><strong>You </strong></td>
				<td>tú, usted</td>
				<td><strong>You</strong> are tall.</td>
				<td>Tú eres alto. / Usted es alto.</td>
			</tr>
			<tr>
				<td><strong>He</strong></td>
				<td>él</td>
				<td><strong>He</strong> is handsome.</td>
				<td>Él es guapo.</td>
			</tr>
			<tr>
				<td><strong>She </strong></td>
				<td>ella</td>
				<td><strong>She</strong> is pretty.</td>
				<td>Ella es guapa.</td>
			</tr>
			<tr>
				<td><strong>It </strong></td>
				<td>ello (neutro)</td>
				<td><strong>It</strong> is cold today.</td>
				<td>Hoy hace frío.</td>
			</tr>
			<tr>
				<td><strong>We </strong></td>
				<td>nosotros</td>
				<td><strong>We</strong> are tired.</td>
				<td>Nosotros estamos cansados.</td>
			</tr>
			<tr>
				<td><strong>You </strong></td>
				<td>vosotros, ustedes</td>
				<td><strong>You</strong> are angry.</td>
				<td>Vosotros estáis enfadados. Ustedes están enfadados.</td>
			</tr>
			<tr>
				<td><strong>They </strong></td>
				<td>ellos, ellas</td>
				<td><strong>They</strong> are at the cinema.</td>
				<td>Ellos están en el cine.</td>
			</tr>
			<tr class="principal">
				<td colspan="2">Pronombres personales<br>(función de objeto)</td>
				<td>Ejemplo</td>
				<td>&nbsp;Traducción ejemplo</td>
			</tr>
			<tr>
				<td><strong>Me </strong></td>
				<td>mí</td>
				<td>Can you help <strong>me</strong>?</td>
				<td>¿Puedes ayudarme?</td>
			</tr>
			<tr>
				<td><strong>You </strong></td>
				<td>a tí, a usted</td>
				<td>I can help <strong>you</strong>.</td>
				<td>Puedo ayudarte. / Puedo ayudarle.</td>
			</tr>
			<tr>
				<td><strong>Him </strong></td>
				<td>a él</td>
				<td>Can you see <strong>him</strong>?</td>
				<td>¿Le puedes ver?</td>
			</tr>
			<tr>
				<td><strong>Her </strong></td>
				<td>a ella</td>
				<td>Give it to <strong>her</strong>.</td>
				<td>Dáselo a ella.</td>
			</tr>
			<tr>
				<td><strong>It </strong></td>
				<td>a ello</td>
				<td>Give <strong>it</strong> a kick.</td>
				<td>Dale una patada.</td>
			</tr>
			<tr>
				<td><strong>Us </strong></td>
				<td>a nosotros</td>
				<td>Can you see <strong>us</strong>?</td>
				<td>¿Nos puedes ver?</td>
			</tr>
			<tr>
				<td><strong>You </strong></td>
				<td>a vosotros, a ustedes</td>
				<td>I see <strong>you</strong>.</td>
				<td>Os veo. / Les veo.</td>
			</tr>
			<tr>
				<td><strong>Them </strong></td>
				<td>a ellos</td>
				<td>He can help <strong>them</strong>.</td>
				<td>Les puede ayudar.</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/actividades/_propos.html.erb
<div id="propos">
	<h3>Pronombres Posesivos</h3>
	<table class="tablasaprender table table-striped table-condensed table-hover">
		<tbody>
			<tr class="principal">
				<td colspan="2">Pronombres posesivos<br> (en función de determinante del sujeto)</td>
				<td>Ejemplo</td>
				<td>Traducción ejemplo</td>
			</tr>
			<tr>
				<td><strong>My</strong></td>
				<td>mi, mis</td>
				<td>This is <strong>my</strong> house.</td>
				<td>Ésta es mi casa.</td>
			</tr>
			<tr>
				<td><strong>Your</strong></td>
				<td>tu, tus (de ti) / su, sus (de usted)</td>
				<td>This is <strong>your</strong> book.</td>
				<td>Éste es tu libro. / Éste es su libro.</td>
			</tr>
			<tr>
				<td><strong>His </strong></td>
				<td>su, sus (de él)</td>
				<td>This is <strong>his</strong> bicycle.</td>
				<td>Ésta es su bicicleta.</td>
			</tr>
			<tr>
				<td><strong> Her </strong></td>
				<td>su, sus (de ella)</td>
				<td>This is <strong>her</strong> dress.</td>
				<td>Éste es su vestido.</td>
			</tr>
			<tr>
				<td><strong> Its </strong></td>
				<td>su, sus</td>
				<td>This is <strong>its</strong> (the cat's) home.</td>
				<td>Ésta es su casa. (la casa del gato)</td>
			</tr>
			<tr>
				<td><strong> Our </strong></td>
				<td>nuestro/a, nuestros/as</td>
				<td>These are <strong>our</strong> suitcases.</td>
				<td>Éstas son nuestras maletas.</td>
			</tr>
			<tr>
				<td><strong> Your </strong></td>
				<td><p>vuestro/a, vuestros/as, su, <br>sus (de ustedes)</p></td>
				<td>These are <strong>your</strong> seats.</td>
				<td>Éstos son vuestros asientos. Éstos son sus asientos.</td>
			</tr>
			<tr>
				<td><strong> Their </strong></td>
				<td>su, sus (de ellos)</td>
				<td>These are <strong>their</strong> books.</td>
				<td>Éstos son sus libros.</td>
			</tr>
			<tr class="principal">
				<td colspan="2">Pronombres posesivos <br> (en función de pronombre)</td>
				<td>Ejemplo</td>
				<td>Traducción ejemplo</td>
			</tr>
			<tr>
				<td><strong>Mine </strong></td>
				<td>mío/s, mía/s</td>
				<td>This book is <strong>mine</strong></td>
				<td>Este libro es mío.</td>
			</tr>
			<tr>
				<td><strong>Yours</strong></td>
				<td>tuyo/s, tuya/s, suyo/s, suya/s</td>
				<td>Is this book <br><strong>yours</strong>?</td>
				<td>¿Este libro es tuyo? / ¿Este libro es suyo?</td>
			</tr>
			<tr>
				<td><strong>His </strong></td>
				<td>suyo/s, suya/s<br> (de el)</td>
				<td>This bicycle is <strong>his</strong>.</td>
				<td>Esta bicicleta es de él.</td>
			</tr>
			<tr>
				<td><strong>Hers </strong></td>
				<td>suyo/s, suya/s<br> (de ella)</td>
				<td>The dress is <strong>hers</strong>.</td>
				<td>El vestido es de ella.</td>
			</tr>
			<tr>
				<td><strong>Its</strong></td>
				<td>su, sus</td>
				<td>The house is <strong>its</strong> (the cat's).</td>
				<td>La casa es suya (del gato).</td>
			</tr>
			<tr>
				<td><strong>Ours </strong></td>
				<td>nuestro/s, nuestra/s</td>
				<td>The suitcases are <strong>ours</strong>.</td>
				<td>Las maletas son nuestras.</td>
			</tr>
			<tr>
				<td><strong>Yours </strong></td>
				<td>vuestro/a, vuestros/as, suyo/s, suya/s</td>
				<td>These seats are<strong> yours</strong>.</td>
				<td>Estos asientos son vuestros. Estos asientos son suyos.</td>
			</tr>
			<tr>
				<td><strong>Theirs </strong></td>
				<td>suyo/a, suyos/as (de ellos)</td>
				<td>This pencil is <strong>theirs</strong>.</td>
				<td>Este lápiz es de ellos.</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/actividades/_proref.html.erb
<div id="proref">
	<h3>Pronombres Reflexivos</h3>
</div>

app/views/actividades/index.html.erb
<head>
	<%= stylesheet_link_tag    "actividades", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "actividades", "data-turbolinks-track" => true %>
</head>

<div class="divpadding">
	<%= link_to "<-- Regresar", "/", :class => "btn btn-mini" %>
	<p>
		<h1 class="titulo">Actividades</h1>
		<div>
			<ol>
				<a class="vinculo" id="properli"/><li>Pronombres personales</li></a>
				<a class="vinculo" id="proposli"><li>Pronombres posesivos</li></a>
				<a class="vinculo" id="prodemli"><li>Pronombres demostrativos</li></a>
				<a class="vinculo" id="tabproli"><li>Tabla de pronombres</li></a>
				<li><%= link_to "Ver videos", "actividades/videolist" %></li>
				<!-- Basado en: http://www.curso-ingles.com/gramatica-inglesa/pronombres-personales.php -->
			</ol>
		</div>
		<div id="partials">
			<%= render "prodem" %>
			<%= render "proper" %>
			<%= render "propos" %>
			<%= render "proref" %>
			<%= render "tabpro" %>
		</div>
	</p>
</div>

app/views/actividades/seleccion.html.erb
        <div class="divpadding">
        <%= link_to "<-- Regresar", "/", :class => "btn btn-mini" %>
        <div class="dom-body-text paragraph" style="margin-left:-2%">
          <p>Juegos</p>
        </div>
        <div class="rectangle rectangle-1 rectangle-5">
          <h3 class="heading" style="margin-left:5%">Elija un juego: </h3>
          <div class="btn-group" style="margin-left:20%">
            <a href="/hangman"><button class="btn btn-danger">Hangman</button></a>
            <a href="/tuttifrutti"><button class="btn btn-primary">Tuttifrutti</button></a>
          </div>
        </div>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th class="th-1">Puntos Publicos</th>
              <th>Puntos Privados</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= current_user.puntosPublicos %></td>
              <td><%= current_user.puntosPrivados %></td>
            </tr>
          </tbody>
        </table>

app/views/actividades/videolist.html.erb
<div class="divpadding">
<%= link_to "<-- Regresar", "/actividades", :class => "btn btn-mini" %>
<p>
<h1>Lista de videos: </h1>
<strong>Cada video completamente visto otorga 20 puntos publicos.</strong>
<p>
<%= form_tag actividades_videolist_path, :method => 'post' do %>
<select name="cantidad" style="width:50px">
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
</select>
<br />
<input type="submit" value="Limitar cantidad listada" class="btn btn-warning" />
<% end %>
</p>

<div id='outer'>
<% @videos.each do |video| %>
    <center>
    <div class='tile'>
    <%= link_to "#{image_tag(video.thumbnails.first.url)}".html_safe, actividades_video_path(:videoid => video.unique_id), :method => :post %> <br/> <%= video.title %> </div>
    </center>
<% end %>
</div>

</div>

app/views/lists/edit.html.erb
<div class="divpadding">
<%= link_to "<-- Regresar", "/lists", :class => "btn btn-mini" %>
<p>
<h1>Editar Lista</h1>
</p>

<%= form_for :list, url: list_path(@list.id), method: :patch do |f| %>
  <% if @list.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@list.errors.count, "error") %> prohibited
      this list from being saved:</h2>
    <ul>
    <% @list.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :nombre, "Nombre: " %>
    <%= f.text_field :nombre %>
  </p>
 
  <p>
    <%= f.label :idiomaNativo, "Idioma Nativo: " %>
    <%= f.text_area :idiomaNativo %>
  </p>
  
  <p>
    <%= f.label :idiomaForaneo, "Idioma Foraneo: " %>
    <%= f.text_field :idiomaForaneo %>
  </p>
 
  <p>
    <%= f.submit "Editar Lista", :class => "btn btn-success" %>
  </p>
<% end %>
</div>

app/views/lists/index.html.erb
<div class="dom-body-text paragraph">
<%= link_to "<-- Regresar", "/", :class => "btn btn-mini" %>
<p>
<h1>Mostrando listas de <%= current_user.nombre %>: </h1>
<br />
 
<center>
<table id="listas" class="table table-striped table-condensed table-hover">
<thead>
  <tr>
    <th>Nombre</th>
    <th>Idioma Nativo</th>
    <th>Idioma Foraneo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 </thead>
 <tbody>
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.nombre %></td>
      <td><%= list.idiomaNativo %></td>
      <td><%= list.idiomaForaneo %></td>
      <td><%= link_to 'Ver', list_path(list), class: "btn btn-info btn-mini" %></td>
      <td><%= link_to 'Editar', edit_list_path(list), class: "btn btn-mini"  %></td>
      <td><%= link_to 'Borrar', list_path(list), class: "btn btn-danger btn-mini", method: :delete, data: { confirm: 'Pulsa OK para confirmar el borrado de la lista' } %></td>
    </tr>
  <% end %>
</tbody>
</table>
</center>

<p>
<%= button_to 'Lista Nueva', new_list_path, class: "btn btn-warning", style: "margin-left:45%",  :method => :get %>
</p>
</div>

app/views/users/menu.html.erb
    <!-- <div id="page-wrapper">
    <div id="absolute-wrapper"> -->
        <!-- <div class="rectangle rectangle-1 rectangle-2 rectangle-3">
          <h1 class="heading">Sistema de Auto Aprendizaje de Idiomas</h1>
        </div>
        <div class="rectangle rectangle-2 rectangle-4">
          <img src="images/black_invert_30x40.png" class="image">
        </div> -->
        <div class="dom-body-text paragraph">
          <p>Bienvenido al SAAI, <%= current_user.nombre %>!</p>
        </div>
        <div class="rectangle rectangle-1 rectangle-5">
          <h3 class="heading">Que te gustaría hacer?&nbsp;</h3>
          <div class="btn-group">
            <a href="/seleccion"><button class="btn btn-primary">Jugar</button></a>
            <a href="/lists"><button class="btn btn-warning">Listas de Vocabulario</button></a>
            <a href="/actividades"><button class="btn btn-danger">Realizar actividades</button></a>
            <%= link_to "Ver Perfil", user_path(current_user), :class => 'btn btn-info' %>
            <a href="/ranking"><button class="btn btn-success">Ver Rankings</button></a>
          </div>
        </div>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th class="th-1">Puntos Publicos</th>
              <th>Puntos Privados</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= current_user.puntosPublicos %></td>
              <td><%= current_user.puntosPrivados %></td>
            </tr>
          </tbody>
        </table>